---
title: Harmony Aikido Foundation
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
url: 
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
- jekyll-feed
navigation:
  main:
  - label: About
    url: "/about"
  - label: Resources
    url: "/resources"
  - label: Community Programs
    url: "#"
    items:
    - label: Campaign
      url: "/you-are-powerful"
    - label: Community Events
      url: "/events"
  - label: Contact
    url: "/contact"
  - label: DONATE TO US
    url: "/support"
  footer:
  - label: About Us
    url: "/about"
  - label: Classes
    url: "#"
  - label: Resources
    url: "/resources"
  - label: Community Programs
    url: "#"
    items:
    - label: Campaign
      url: "/you-are-powerful"
    - label: Community Events
      url: "/events"
