---
title: Harmony Aikido Foundation
email: info@hafusa.org
description: >-
  TBD
baseurl: ""
url: ""
twitter_username: hafusaorg
github_username:  hafusaorg
timezone: PST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
