---
title: Harmony Aikido Foundation
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
url: 
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
- jekyll-feed
subscribe_form:
  mailchimp_list_id: 4000627a40
contact:
  email: info@hafusa.org
navigation:
  call_to_action:
    label: DONATE TO US
    url: "/support"
  main:
  - label: About
    url: "/about"
  - label: Resources
    url: "/resources"
  - label: Community Programs
    url: "#"
    items:
    - label: Campaign
      url: "/you-are-powerful"
    - label: Community Events
      url: "/events"
    - label: Girl Scouts
      url: "/girl-scouts"
  - label: Contact
    url: "/contact"
  footer:
  - label: About
    url: "/about"
  - label: Resources
    url: "/resources"
  - label: Community<br>Programs
    url: "#"
    items:
    - label: Campaign
      url: "/you-are-powerful"
    - label: Community Events
      url: "/events"
    - label: Girl Scouts
      url: "/girl-scouts"
  - label: Contact
    url: "/contact"
