---
title: Harmony Aikido Foundation
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@hafusa.org
description: TBD
baseurl: ''
url: ''
twitter_username: hafusaorg
github_username: hafusaorg
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
